recipe: "regression/v1"
target_col: "quality"
primary_metric: "root_mean_squared_error"
steps:
  ingest: {{INGEST_CONFIG}}
  split:
    # ToDo2: specify split ratios for train, validation, and test sets
    # ...
  transform:
    using: custom
    transformer_method: transformer_fn
  train:
    using: custom
    estimator_method: estimator_fn
    # ToDo9: use the AutoML estimator
    # ...
  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 1
  register:
    allow_non_validated_model: false
  ingest_scoring: {{INGEST_SCORING_CONFIG}}
  predict:
    output: {{PREDICT_OUTPUT_CONFIG}}

# ToDo5: add custom metrics to our recipe
# ...